class CreateHtmlTagsRecords < ActiveRecord::Migration[6.1]
  def up
      HtmlTag.create!(tag_name: '<!--',  description:'	Describe a comment text in the source code')
      HtmlTag.create!(tag_name: '<!doctype',  description:'	Defines a document type')
      HtmlTag.create!(tag_name: '<a',  description:'	Specific a anchor (Hyperlink) Use for link in internal/external web documents.')
      HtmlTag.create!(tag_name: '<abbr',  description:'	Describes an abbreviation (acronyms)')
      HtmlTag.create!(tag_name: '<acronym',  description:'	Describes an acronyms')
      HtmlTag.create!(tag_name: '<address',  description:'	Describes an address information')
      HtmlTag.create!(tag_name: '<applet',  description:'	Embedding an applet in HTML document')
      HtmlTag.create!(tag_name: '<area',  description:'	Defines an area in an image map')
      HtmlTag.create!(tag_name: '<article',  description:'	Defines an article')
      HtmlTag.create!(tag_name: '<aside',  description:'	Describes contain set(or write) on aside place in page contain')
      HtmlTag.create!(tag_name: '<audio',  description:'	Specific audio content')
      HtmlTag.create!(tag_name: '<b',  description:'	Specific text weight bold')
      HtmlTag.create!(tag_name: '<base',  description:'	Define a base URL for all the links with in a web page')
      HtmlTag.create!(tag_name: '<basefont',  description:'	Describes a default font color, size, face in a document')
      HtmlTag.create!(tag_name: '<bb',  description:'	Define browser command, that command invoke as per client action')
      HtmlTag.create!(tag_name: '<bdo',  description:'	Specific direction of text display')
      HtmlTag.create!(tag_name: '<big',  description:'	Defines a big text')
      HtmlTag.create!(tag_name: '<blockquote',  description:'	Specifies a long quotation')
      HtmlTag.create!(tag_name: '<body',  description:'	Defines a main section(body) part in HTML document')
      HtmlTag.create!(tag_name: '<br',  description:'	Specific a single line break')
      HtmlTag.create!(tag_name: '<button',  description:'	Specifies a press/push button')
      HtmlTag.create!(tag_name: '<canvas',  description:'	Specifies the display graphics on HTML web documment	')
      HtmlTag.create!(tag_name: '<caption',  description:'	Define a table caption')
      HtmlTag.create!(tag_name: '<center',  description:'	Specifies a text is display in center align')
      HtmlTag.create!(tag_name: '<cite',  description:'	Specifies a text citation')
      HtmlTag.create!(tag_name: '<code',  description:'	Specifies computer code text')
      HtmlTag.create!(tag_name: '<col',  description:'	Specifies a each column within a colgroup element in table')
      HtmlTag.create!(tag_name: '<colgroup',  description:'	Defines a group of one or more columns inside table')
      HtmlTag.create!(tag_name: '<command',  description:'	Define a command button, invoke as per user action')
      HtmlTag.create!(tag_name: '<datagrid',  description:'	Define a represent data in datagrid either list wise or tree wise')
      HtmlTag.create!(tag_name: '<datalist',  description:'	Define a list of pre-defined options surrounding input tag')
      HtmlTag.create!(tag_name: '<dd',  description:'	Defines a definition description in a definition list')
      HtmlTag.create!(tag_name: '<del',  description:'	Specific text deleted in web document')
      HtmlTag.create!(tag_name: '<details',  description:'	Define a additional details hide or show as per user action')
      HtmlTag.create!(tag_name: '<dfn',  description:'	Define a definition team')
      HtmlTag.create!(tag_name: '<dialog',  description:'	Define a chat conversation between one or more person')
      HtmlTag.create!(tag_name: '<dir',  description:'	Define a directory list')
      HtmlTag.create!(tag_name: '<div',  description:'	Define a division part')
      HtmlTag.create!(tag_name: '<dl',  description:'	Define a definition list')
      HtmlTag.create!(tag_name: '<dt',  description:'	Define a definition team')
      HtmlTag.create!(tag_name: '<em',  description:'	Define a text is emphasize format')
      HtmlTag.create!(tag_name: '<embed',  description:'	Define a embedding external application using a relative plug-in')
      HtmlTag.create!(tag_name: '<eventsource',  description:'	Defines a source of event generates to remote server')
      HtmlTag.create!(tag_name: '<fieldset',  description:'	Defines a grouping of related form elements')
      HtmlTag.create!(tag_name: '<figcaption',  description:'	Represents a caption text corresponding with a figure element')
      HtmlTag.create!(tag_name: '<figure',  description:'	Represents self-contained content corresponding with a figcaption element')
      HtmlTag.create!(tag_name: '<font',  description:'	Defines a font size, font face and font color for its text')
      HtmlTag.create!(tag_name: '<footer',  description:'	Defines a footer section containing details about the author, copyright, contact us, sitemap, or links to related documents.')
      HtmlTag.create!(tag_name: '<form',  description:'	Defines a form section that having interactive input controls to submit form information to a server.')
      HtmlTag.create!(tag_name: '<frame',  description:'	Defines frame window.')
      HtmlTag.create!(tag_name: '<frameset',  description:'	Used to holds one or more frame elements.')
      HtmlTag.create!(tag_name: '<h',  description:'	Defines a Headings level from 1 to 6 different sizes.')
      HtmlTag.create!(tag_name: '<head',  description:'	Defines header section of HTML document.')
      HtmlTag.create!(tag_name: '<header',  description:'	Defines as a container that hold introductory content or navigation links.')
      HtmlTag.create!(tag_name: '<hgroup',  description:'	Defines the heading of a section that hold the h1 to h6 tags.')
      HtmlTag.create!(tag_name: '<hr /',  description:'	Represent a thematic break between paragraph-level tags. It is typically draw horizontal line.')
      HtmlTag.create!(tag_name: '<html',  description:'	Define a document is a HTML markup language')
      HtmlTag.create!(tag_name: '<i',  description:'	Defines a italic format text')
      HtmlTag.create!(tag_name: '<iframe',  description:'	Defines a inline frame that embedded external content into current web document.')
      HtmlTag.create!(tag_name: '<img',  description:'	Used to insert image into a web document.')
      HtmlTag.create!(tag_name: '<input',  description:'	Define a get information in selected input')
      HtmlTag.create!(tag_name: '<ins',  description:'	Used to indicate text that is inserted into a page and indicates changes to a document.')
      HtmlTag.create!(tag_name: '<isindex',  description:'	Used to create a single line search prompt for querying the contents of the document.')
      HtmlTag.create!(tag_name: '<kbd',  description:'	Used to identify text that are represents keyboard input.')
      HtmlTag.create!(tag_name: '<keygen',  description:'	Used to generate signed certificate, which is used to authenticate to services.')
      HtmlTag.create!(tag_name: '<label',  description:'	Used to caption a text label with a form input element.')
      HtmlTag.create!(tag_name: '<legend',  description:'	Used to add a caption (title) to a group of related form elements that are grouped together into the fieldset tag.')
      HtmlTag.create!(tag_name: '<li',  description:'	Define a list item either ordered list or unordered list.')
      HtmlTag.create!(tag_name: '<link',  description:'	Used to load an external stylesheets into HTML document.')
      HtmlTag.create!(tag_name: '<map',  description:'	Defines an clickable image map.')
      HtmlTag.create!(tag_name: '<mark',  description:'	Used to highlighted (marked) specific text.')
      HtmlTag.create!(tag_name: '<menu',  description:'	Used to display a unordered list of items/menu of commands.')
      HtmlTag.create!(tag_name: '<meta',  description:'	Used to provide structured metadata about a web page.')
      HtmlTag.create!(tag_name: '<meter',  description:'	Used to measure data within a given range.')
      HtmlTag.create!(tag_name: '<nav',  description:'	Used to defines group of navigation links.')
      HtmlTag.create!(tag_name: '<noframes',  description:'	Used to provide a fallback content to the browser that does not support the frame element.')
      HtmlTag.create!(tag_name: '<noscript',  description:'	Used to provide an fall-back content to the browser that does not support the JavaScript.')
      HtmlTag.create!(tag_name: '<object',  description:'	Used to embedded objects such as images, audio, videos, Java applets, and Flash animations.')
      HtmlTag.create!(tag_name: '<ol',  description:'	Defines an ordered list of items.')
      HtmlTag.create!(tag_name: '<optgroup',  description:'	Used to create a grouping of options, the related options are grouped under specific headings.')
      HtmlTag.create!(tag_name: '<option',  description:'	Represents option items within a select, optgroup or datalist element.')
      HtmlTag.create!(tag_name: '<output',  description:'	Used for representing the result of a calculation.')
      HtmlTag.create!(tag_name: '<p',  description:'	Used to represents a paragraph text.')
      HtmlTag.create!(tag_name: '<param',  description:'	Provides parameters for embedded object element.')
      HtmlTag.create!(tag_name: '<pre',  description:'	Used to represents preformatted text.')
      HtmlTag.create!(tag_name: '<progress',  description:'	Represents the progress of a task.')	
      HtmlTag.create!(tag_name: '<q',  description:'	Represents the short quotation.')
      HtmlTag.create!(tag_name: '<rp',  description:'	Used to provide parentheses around fall-back content to the browser that does not support the ruby annotations.')
      HtmlTag.create!(tag_name: '<rt',  description:'	Specifies the ruby text of ruby annotation.')
      HtmlTag.create!(tag_name: '<ruby',  description:'	Used to represents a ruby annotation.')
      HtmlTag.create!(tag_name: '<s',  description:'	Text display in strikethrough style.')
      HtmlTag.create!(tag_name: '<samp',  description:'	Represents text that should be interpreted as sample output from a computer program.')
      HtmlTag.create!(tag_name: '<script',  description:'	Defines client-side JavaScript.')
      HtmlTag.create!(tag_name: '<section',  description:'	Used to divide a document into number of different generic section.')
      HtmlTag.create!(tag_name: '<select',  description:'	Used to create a drop-down list.')
      HtmlTag.create!(tag_name: '<small',  description:'	Used to makes the text one size smaller.')
      HtmlTag.create!(tag_name: '<source',  description:'	Used to specifies multiple media resources.')
      HtmlTag.create!(tag_name: '<span',  description:'	Used to grouping and applying styles to inline elements.')
      HtmlTag.create!(tag_name: '<strike',  description:'	Represents strikethrough text.')
      HtmlTag.create!(tag_name: '<strong',  description:'	Represents strong emphasis greater important text.')
      HtmlTag.create!(tag_name: '<style',  description:'	Used to add CSS style to an HTML document.')
      HtmlTag.create!(tag_name: '<sub',  description:'	Represents inline subscript text.')
      HtmlTag.create!(tag_name: '<sup',  description:'	Represents inline superscript text.')
      HtmlTag.create!(tag_name: '<table',  description:'	Used to defines a table in an HTML document.')
      HtmlTag.create!(tag_name: '<tbody',  description:'	Used for grouping table rows.')
      HtmlTag.create!(tag_name: '<td',  description:'	Used for creates standard data cell in HTML table.')
      HtmlTag.create!(tag_name: '<textarea',  description:'	Create multi-line text input.')
      HtmlTag.create!(tag_name: '<tfoot',  description:'	Used to adding a footer to a table that containing summary of the table data.')
      HtmlTag.create!(tag_name: '<th',  description:'	Used for creates header of a group of cell in HTML table.')
      HtmlTag.create!(tag_name: '<thead',  description:'	Used to adding a header to a table that containing header information of the table.')
      HtmlTag.create!(tag_name: '<time',  description:'	Represents the date and/or time in an HTML document.')
      HtmlTag.create!(tag_name: '<title',  description:'	Represents title to an HTML document.')
      HtmlTag.create!(tag_name: '<tr',  description:'	Defines a row of cells in a table.')
      HtmlTag.create!(tag_name: '<track',  description:'	Represents text tracks for both the audio and video tags.')
      HtmlTag.create!(tag_name: '<tt',  description:'	Represents teletype text.')
      HtmlTag.create!(tag_name: '<u',  description:'	Represents underlined text.')
      HtmlTag.create!(tag_name: '<ul',  description:'	Defines an unordered list of items.')
      HtmlTag.create!(tag_name: '<var',  description:'	Represents a variable in a computer program or mathematical equation.')
      HtmlTag.create!(tag_name: '<video',  description:'	Used to embed video content.')
      HtmlTag.create!(tag_name: '<wbr',  description:'	 Defines a word break opportunity in a long string of text.')
  end

  def down
    tags = HtmlTag.all
    if !tags.nil
      tags.each do |tag|
        tag.destroy
      end
    end
  end
end
